# Video Ayarları
hwdec=auto
gpu-context=wayland

# Altyazı Ayarları
sub-font='Comfortaa'
sub-bold=yes
sub-font-size=40
sub-color='#FFFFFFFF'
sub-border-color='#FF000000'
sub-border-size=2
sub-shadow-offset=1
sub-shadow-color='#33000000'
sub-spacing=0.5
sub-margin-y=36

# Pencere Ayarları
autofit-larger=90%x90%
keep-open=yes
cursor-autohide=1000

# Ses Ayarları
volume-max=200
volume=100

# Dil Ayarları
slang=tr,en
alang=en,tr
